import type { Metadata } from "next"; //SEO wali information ke liye (title, description)
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; //poori website ki CSS file

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function Navbar() {
 return (
    <nav style={{padding:"15px", background:"#111", color:"#fff"}}>
      <h2>My Website</h2>
    </nav>
  );
};

export function Footer() {
  return(
    <footer style={{background:"#111", color:"#ffff", padding:"15px"}}>
      <p>© 2024 My Website. All rights reserved.</p>
    </footer>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
